name: Pipeline CI - Build y Test

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mostrar estructura (debug)
        run: ls -R

      - name: Instalar dependencias
        run: |
          pwd
          npm install

      - name: Ejecutar tests
        run: |
          pwd
          node test/test.js
